### ISSUE TITLE
📱모바일 기기에서 수평 스크롤 없애기

### ISSUE THREAD

**Issue by eunnbi** [eunnbi/bookmark#16]
아래 css 코드 적용

```css
html,
body,
#root {
  max-width: 100%;
  overflow-x: hidden;
}
```
